BackendBundle\Entity\Announcement:
    type: entity
    table: Announcement
    indexes:
        CategoryFK_idx:
            columns:
                - categoryId
        Announcement_PlayerPosition_FK:
            columns:
                - playerPositionId
        Announcement_Role_FK:
            columns:
                - searchedRoleId
    id:
        announcementid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: announcementId
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        userid:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: userId
        publicationdate:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: publicationDate
        active:
            type: boolean
            nullable: true
            options:
                default: '1'
        modified:
            type: boolean
            nullable: true
            options:
                default: '0'
        categoryid:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: categoryId
        photo:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        playerpositionid:
            targetEntity: Playerposition
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                playerPositionId:
                    referencedColumnName: playerPositionId
            orphanRemoval: false
        searchedroleid:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                searchedRoleId:
                    referencedColumnName: roleId
            orphanRemoval: false
    lifecycleCallbacks: {  }
