BackendBundle\Entity\Club:
    type: entity
    table: Club
    id:
        clubid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: clubId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        shield:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        initials:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: 'Siglas del club'
        location:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        province:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
