BackendBundle\Entity\Country:
    type: entity
    table: Country
    id:
        countryid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: countryId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        noc:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: Abreviación
            column: NOC
        flag:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
