BackendBundle\Entity\Playerposition:
    type: entity
    table: PlayerPosition
    id:
        playerpositionid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: playerPositionId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        abbrev:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        active:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
