BackendBundle\Entity\Playerpositionperuser:
    type: entity
    table: PlayerPositionPerUser
    indexes:
        PlayerPositionPerUser_UserFK:
            columns:
                - userId
    id:
        playerpositionid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: playerPositionId
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: userId
    fields:
        prefered:
            type: boolean
            nullable: true
        active:
            type: boolean
            nullable: true
            options:
                default: '1'
    lifecycleCallbacks: {  }
