BackendBundle\Entity\Reactedannouncement:
    type: entity
    table: reactedannouncement
    indexes:
        UserFK_idx:
            columns:
                - userId
        AnnouncementFK_idx:
            columns:
                - announcementId
    id:
        reactedannouncementid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: reactedAnnouncementId
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: userId
        liked:
            type: boolean
            nullable: true
        interested:
            type: boolean
            nullable: true
        moment:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
        active:
            type: boolean
            nullable: true
    manyToOne:
        announcementid:
            targetEntity: Announcement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                announcementId:
                    referencedColumnName: announcementId
            orphanRemoval: false
    lifecycleCallbacks: {  }
