BackendBundle\Entity\Requestedannouncement:
    type: entity
    table: RequestedAnnouncement
    indexes:
        UserFK_idx:
            columns:
                - userId
        AnnouncementFK_idx:
            columns:
                - announcementId
    id:
        requestedannouncementid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: requestedAnnouncementId
            generator:
                strategy: IDENTITY
    fields:
        announcementid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: announcementId
        userid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: userId
        requested:
            type: boolean
            nullable: true
        moment:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
        active:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
