BackendBundle\Entity\Searchhistory:
    type: entity
    table: searchhistory
    indexes:
        UserFK_idx:
            columns:
                - userId
    id:
        searchhistoryid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: searchHistoryId
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: userId
        moment:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        searchedtext:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: searchedText
        active:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
