BackendBundle\Entity\User:
    type: entity
    table: User
    indexes:
        CountryFK_idx:
            columns:
                - countryId
        Population_idx:
            columns:
                - populationId
        RoleFK_idx:
            columns:
                - roleId
        User_PlayerPosition_FK:
            columns:
                - playerPositionId
    id:
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: userId
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: userName
        surname:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        roleid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: roleId
        email:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        active:
            type: boolean
            nullable: true
        birthdate:
            type: date
            nullable: true
            column: birthDate
        age:
            type: integer
            nullable: true
            options:
                unsigned: false
        countryid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: countryId
        populationid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: populationId
        profilephoto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: profilePhoto
        height:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        weight:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
        bio:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        sex:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
        foot:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
        playerpositionid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: playerPositionId
        historial:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        clubid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: clubId
    lifecycleCallbacks: {  }
