default_index:
  path: /
  defaults: { _controller: "AppBundle:Default:index"}
  methods: GET

default_roles:
  path: /roles
  defaults: { _controller: "AppBundle:Default:roles"}
  methods: GET

default_login:
  path: /login
  defaults: { _controller: "AppBundle:User:login"}
  methods: POST

default_user:
  path: /user
  defaults: { _controller: "AppBundle:User:user"}
  methods: POST

user_show:
  path: /user/{id}
  defaults: { _controller: "AppBundle:User:show", id : 1}
  methods: GET

announcement_show:
  path: /announcement/{id}
  defaults: { _controller: "AppBundle:Announcement:show", id : null}
  methods: GET

default_announcement:
  path: /announcement
  defaults: { _controller: "AppBundle:Announcement:announcement"}
  methods: GET