default_index:
  path: /
  defaults: { _controller: "AppBundle:Default:index"}
  methods: GET

default_roles:
  path: /roles
  defaults: { _controller: "AppBundle:Default:roles"}
  methods: GET

default_login:
  path: /login
  defaults: { _controller: "AppBundle:User:login"}
  methods: POST

default_user:
  path: /user
  defaults: { _controller: "AppBundle:User:user"}
  methods: POST

user_show:
  path: /user/{id}
  defaults: { _controller: "AppBundle:User:show", id : null}
  methods: GET

announcement_show:
  path: /announcement/{id}
  defaults: { _controller: "AppBundle:Announcement:show", id : null}
  methods: GET

default_announcement:
  path: /announcement
  defaults: { _controller: "AppBundle:Announcement:announcement"}
  methods: POST

announcements_shows:
  path: /announcement/
  defaults: { _controller: "AppBundle:Announcement:shows"}
  methods: GET

announcements_user_show:
  path: /announcementPerUser/{user_token}
  defaults: { _controller: "AppBundle:Announcement:showUserAnnouncements", user_token : null}
  methods: GET

announcements_user_show_alter:
  path: /announcementPerUser/
  defaults: { _controller: "AppBundle:Announcement:showUserAnnouncements", user_token : null}
  methods: GET

default_playerpositionperuser_show:
  path: /playerpositionperuser/{userid}
  defaults: { _controller: "AppBundle:Playerpositionperuser:show", userid : 1}
  methods: GET

default_playerpositionperuser_post:
  path: /playerpositionperuser
  defaults: { _controller: "AppBundle:Playerpositionperuser:playerpositionperuser"}
  methods: POST

default_clubhistoryperuser_post:
  path: /clubhistoryperuser
  defaults: { _controller: "AppBundle:Clubhistoryperuser:clubhistoryperuser"}
  methods: POST

default_clubhistoryperuser_show:
  path: /clubhistoryperuser/{userid}
  defaults: { _controller: "AppBundle:Clubhistoryperuser:show", userid : 1}
  methods: GET

#reactedAnnouncement con Adonis
default_reactedAnnouncement_show:
  path: /reactedannouncement/{userid}/{interested}
  defaults: { _controller: "AppBundle:Reactedannouncement:show", userid : 1, interested : 2}
  methods: GET

default_reactedAnnouncement_reactedannouncement:
  path: /reactedannouncement
  defaults: { _controller: "AppBundle:Reactedannouncement:reactedannouncement"}
  methods: POST

default_reactedAnnouncement_shownotification:
  path: /reactedannouncementnotification/{userid}
  defaults: { _controller: "AppBundle:Reactedannouncement:showNotifications", userid : 1}
  methods: GET

default_updatereactedAnnouncement_reactedannouncement:
  path: /updatereactedannouncement
  defaults: { _controller: "AppBundle:Reactedannouncement:updatereactedannouncement"}
  methods: POST
#hasta aqui##################  
default_country_showCountries:
  path: /countries/
  defaults: { _controller: "AppBundle:Country:showCountries"}
  methods: GET

#default_country_showPopulations:
 # path: /populations/
  #defaults: { _controller: "AppBundle:Country:showPopulations"}
  #methods: GET

default_population_showPopulations:
  path: /populations/
  defaults: { _controller: "AppBundle:Population:showPopulations"}
  methods: GET

default_role_showRoles:
  path: /roles/
  defaults: { _controller: "AppBundle:Role:showRoles"}
  methods: GET

default_club_showClubs:
  path: /clubs/{clubid}
  defaults: { _controller: "AppBundle:Club:showClubs", clubid : null}
  methods: GET 

default_announcements_role_show:
  path: /announcementPerRole/{roleid}
  defaults: { _controller: "AppBundle:Announcement:showRoleAnnouncements", roleid : 1}
  methods: GET

default_country:
  path: /country/{id}
  defaults: { _controller: "AppBundle:Country:show", id : null}
  methods: GET

default_category_showCategories:
  path: /categories/{categoryid}
  defaults: { _controller: "AppBundle:Category:showCategories", categoryid : null}
  methods: GET

default_contact_showUserContacts:
  path: /contact/{userid}
  defaults: { _controller: "AppBundle:Contactperuser:showUserContacts",userid: null}
  methods: GET

default_contact:
  path: /contact
  defaults: { _controller: "AppBundle:Contactperuser:contact"}
  methods: POST 

default_playerposition_showPositions:
  path: /position/{positionid}
  defaults: { _controller: "AppBundle:Playerposition:showPositions", positionid : null}
  methods: GET 

default_user_deactivate:
  path: /deactivateuser
  defaults: { _controller: "AppBundle:User:deactivateuser"}
  methods: POST