default_index:
  path: /
  defaults: { _controller: "AppBundle:Default:index"}
  methods: GET

default_roles:
  path: /roles
  defaults: { _controller: "AppBundle:Default:roles"}
  methods: GET

default_login:
  path: /login
  defaults: { _controller: "AppBundle:User:login"}
  methods: POST

default_user:
  path: /user
  defaults: { _controller: "AppBundle:User:createUser"}
  methods: POST